export const TYPES = {
    SET_POINTS: 'SET_POINTS',
    SET_MATERIALS: 'SET_MATERIALS',
    SET_FILTERED_MATERIALS: 'SET_FILTERED_MATERIALS',
    SET_IS_LOADING: 'SET_IS_LOADING',
    SET_IS_MATERIAL_MENU_OPEN: 'SET_IS_MATERIAL_MENU_OPEN',
    SET_FURNITURE_NAME: 'SET_FURNITURE_NAME',
    SET_MATERIAL_LAYER: 'SET_MATERIAL_LAYER'
}