export const TYPES = {
    SET_POINTS: 'SET_POINTS',
    SET_MATERIALS: 'SET_MATERIALS',
    SET_FILTERED_MATERIALS: 'SET_FILTERED_MATERIALS',
    SET_IS_LOADING: 'SET_IS_LOADING',
    SET_MATERIAL_LAYER: 'SET_MATERIAL_LAYER',
    SET_INVISIBLE_POINTS: 'SET_INVISIBLE_POINTS' 
}